# -*- coding: utf-8 -*-
"""2557.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vryaYvrPfJLO36piKNS-bRGR8DLP1z7k
"""

print("Hello World!")